### ISSUE TITLE
Removing one domain removes all

### ISSUE THREAD

**Issue by kantaiz3** [silveredgold/beta-protection#16]
Removing one domain in the allow list will remove all domains.

**Comment by silveredgold** [comment]
What browser are you using? I can't reproduce this as clicking the Remove button for me correctly removes just that entry.

**Comment by kantaiz3** [comment]
Google Chrome v106.

Sorry, I forgot to mention that I am using the unpacked `beta-protection-v0.1.7-production.zip` to load the extension and not the `.crx` file. I didn't want to go through the trouble of whitelisting the extensions, so I used the zip. Do those 2 not behave the same?

**Comment by kantaiz3** [comment]
Sorry, I misclicked...

**Comment by silveredgold** [comment]
Oh I can reproduce it now, it's not that it removes all, it removes any entry _after_ the one being deleted, so removing the first one removes all by the looks of it. I'll look into this.

**Comment by kantaiz3** [comment]
You're right!! I always deleted the first item, so I didn't notice.

> I'll look into this.

Thank you!!

**Comment by kantaiz3** [comment]
Thank you so much for fixing this!!
