### ISSUE TITLE
local censoring

### ISSUE THREAD

**Issue by nooblobby1337** [silveredgold/beta-protection#2]
I can't seem to get local censoring to work right, it may be a bug, I set everything up as instructed and everything else works but local censoring when loading in any files just hangs 0/random number loaded into the API ive gotten a few to go through when i only load in like 5-10 at a time so I'm not sure what is wrong, the censor.server is working and looks to be censoring the images but the browser API freezes, I think it is going too fast for itself but it could be a multitude of other reasons...update: I've tested manually and the files it hangs on are pngs with resolutions like 980 x 1900 at 1mb or above.

**Comment by nooblobby1337** [comment]
I think I figured out the issue, there is a 1MB file size limit on the API that cant censor any image above 1MB tested manually.

is that supposed to be there?

**Comment by nooblobby1337** [comment]
it seems it's hanging and won't even start local censoring for any png over 1MB unless you load it in with other viable files then it will cause the API to hang 0/xxx.

**Comment by silveredgold** [comment]
Hmm, what browser are you using? I just tried a few 4MB JPEGs and it worked fine, so just need to check what might be the difference

**Comment by nooblobby1337** [comment]
I am using chrome and your backend, it still hangs on anything over 1.5MB for me, the API does for me anyway, tried reinstalling many times to no avail, so I have just been manually resizing and reformating the images.

**Comment by silveredgold** [comment]
Okay thanks for the extra information, I'll look into it and see what I can work out!

**Comment by silveredgold** [comment]
Just to let you know I can replicate this on my end now and am looking into why it does it. It _should_ currently max out at 4MB (will be upped to 8 in the next update) but something is making the message way bigger than it should be 🤔

**Comment by silveredgold** [comment]
@nooblobby1337 I think I found it! Can you try using the v0.0.7 version of the Beta Censoring backend that was just published? _Theoretically_ it should raise all the limits to ~16MB so larger images should be possible now.

**Comment by nooblobby1337** [comment]
confirmed your fix does work!!! but I have found another "minor" bug with another file folder, upon censoring a folder with 500 files, it had multiple duplicates of jfif and webp and png pictures with the names with endings (1) (2) (3) and will hang if you have multiple duplicates of the same-named pictures of a/or certain file types, i haven't pinpointed what filetype is the culprit but i have a duplicates scanner so its not really an issue for me, but upon duplicate scanning and deleting all duplicates it worked on that folder. almost 100 files of those, 11mb to 2mb files to confirm your fix. confirmed...

**Comment by nooblobby1337** [comment]
and tested on 3 other folders of 1k+

**Comment by silveredgold** [comment]
Awesome, good to know @nooblobby1337 !

I'll look into it on my end but without more information on what's causing it, I'm not sure if I'll be able to narrow down that duplicates behaviour. I know a few other people who have been using local censoring on some big batches so I'll see if they had the same issue. If you do work out more specifically what's causing it, raise an issue or let me know!

Thanks again for reporting this originally!
