### ISSUE TITLE
Can't connect to backend

### ISSUE THREAD

**Issue by thinkerdevoe4** [silveredgold/beta-protection#25]
Keep getting the message "Error: Failed to start the connection: Error: WebSocket failed to connect. The connection could not be found on the server, either the endpoint may not be a SignalR endpoint, the connection ID is not present on the server, or there is a proxy blocking WebSockets. If you have multiple servers check that sticky sessions are enabled.", address is http://localhost:2382 but it's not connecting to the backend.

**Comment by silveredgold** [comment]
Is the backend running? That message just means that when the extension tries to contact the backend, it doesn't respond. If you don't have the backend running locally on your PC you need to either a) run it, or b) update the host in the settings to point to a running backend.

**Comment by silveredgold** [comment]
Closing from no response. Either re-open this issue or open a new issue with the requested information if the issue persists.

**Comment by seninwastaken** [comment]
I have this same issue but I don't know how to solve it
