### ISSUE TITLE
Chrome-Extention doesn't work on Chrome (Kiwi) @ Android

### ISSUE THREAD

**Issue by eliaskyt** [silveredgold/beta-protection#27]
Hey there! The extention doesn't work on the Chrome-based-Browser Kiwi, that's recommended in the Android-Install-Guilde.
I can't see and problems and configured all as you said in the config-guide.

Dear Wishes

**Comment by silveredgold** [comment]
What about it doesn't work?

**Comment by silveredgold** [comment]
Closing from no response. Either re-open this issue or open a new issue with the requested information if the issue persists.
