### ISSUE TITLE
The extension isn't passing any images to the back end

### ISSUE THREAD

**Issue by InterUser82** [silveredgold/beta-protection#28]
The extension isn't passing requests on to the back end.

The back end seem to be working fine. When it receives requests, it works as expected.

My back end is Beta Censoring. I'm using Chrome. Censoring Mode is in "Enabled". 

When I use either Right Click -> "Censor This Image" or Local Censoring, the back end censors the images as expected. 

My Placeholders also work as expected when using Right Click ->  "Censor This Image".

It's like the extension isn't reading the images displayed in the  browser at all.

**Comment by silveredgold** [comment]
That's a new one. Try changing the extension mode to Disabled, reload the page, then change back to Enabled and reload again and see if that changes anything?

**Comment by silveredgold** [comment]
Closing from no response. Either re-open this issue or open a new issue with the requested information if the issue persists.
