### ISSUE TITLE
Brave import not working

### ISSUE THREAD

**Issue by GoneWide** [silveredgold/beta-protection#3]
Brave browser upload and import of placeholder images doesn't work.
When I press any "Import" button, nothing happens.

Tested with Google Chrome on the same system and import works there.

**Comment by silveredgold** [comment]
This is covered in the docs [here in the Troubleshooting section](https://silveredgold.github.io/beta-protection/guide/installation.html#can-t-import-placeholders-or-censor-local-images-with-brave)

The Brave developers have disabled the standard File System Access APIs that every other browser uses, even for extensions. It's extremely unclear why they do this, and I can't change that from my end.
