### ISSUE TITLE
Switching cencoring mode from on demand to disabled/enabled does not persist after closing extension pop-up

### ISSUE THREAD

**Issue by rsmazrab** [silveredgold/beta-protection#30]
This is for version 0.2, which I installed from unpacked folder. I'm on a mac

Sorry if formatting is unprofessional, let me know if you need more details

**Comment by silveredgold** [comment]
You're right, that's not working right. Let me look into it.

**Comment by silveredgold** [comment]
This should be resolved in `v0.2.1`. Thanks for reporting 👍
