### ISSUE TITLE
Issue with new features for local censoring - can't enable both

### ISSUE THREAD

**Issue by jesseluvsheels** [silveredgold/beta-protection#32]
You can enable one (doesn't matter which) and it works, can't disable it.
If you then try and enable the other, it does enable, but it disables the first one.
eg; enable "Force overwriting local images" and it is enabled. Then enable "Overwrites apply to local censoring" and it enables OK, however, "Force overwriting local images" is now disabled.
![image](https://user-images.githubusercontent.com/106543602/218083845-dffd3889-d581-49e8-824c-f9facd36d00a.png)
![image](https://user-images.githubusercontent.com/106543602/218083939-d5f812c5-2e89-4307-b1e7-f21c75ae3853.png)
First thing I checked, me being me ;)

**Comment by silveredgold** [comment]
Hmmm, that's odd, but not something I tested for. I'll have to look into that.

**Comment by silveredgold** [comment]
Should be fixed in `v0.2.2` Upgrade and let me know if you still run into problems.
