### ISSUE TITLE
Video options locked by overide, still changeable from extension menu

### ISSUE THREAD

**Issue by jesseluvsheels** [silveredgold/beta-protection#34]
Video options are set in an overide, locked on the main extension page, however in the drop down menu for the extension, I can change the video censoring option, see picture;
![image](https://user-images.githubusercontent.com/106543602/218237411-1ae931f0-4cdc-42c8-88af-2e52775874dd.png)

using v0.2.2

**Comment by silveredgold** [comment]
Found the problem, simple enough fix, will go out with the next update. Thanks for the report!
