### ISSUE TITLE
2.2 crashed Vivaldi when beta-protection "options" are opened

### ISSUE THREAD

**Issue by nisaeggu** [silveredgold/beta-protection#37]
I've been using 1.7 in Vivaldi for a long while now and installed 2.2 recently, but now if I open the "options" of beta-protection Vivaldi crashes consistently. Censoring does still works, though no customizations in the options due to the crashing.

**Comment by silveredgold** [comment]
Thanks for the report, I don't use Vivaldi myself so hadn't tested this. I'm still working on some updates to 0.2.x, so I'll try and work out what's going on here.

**Comment by silveredgold** [comment]
I just fired up Vivaldi on my PC (5.7 on Win10) and using v0.2.4 of Beta Protection and it seems to work fine browsing the options. Can you try it again with the latest version and see if it works now?

Alternatively, you can also try uninstalling and reinstalling the extension to see if that clears it up.
