### ISSUE TITLE
Censoring speed is not fast enough and leads to uncensored images leaking.

### ISSUE THREAD

**Issue by tachangan** [silveredgold/beta-protection#39]
In order to prevent people from seeing uncensored images, placeholders should be placed on those first when censorship occurs. But, I've discovered that right before it occurs, uncensored photographs would briefly show up. The users' desires for a severe vision restriction are obviously ruined.

I also hope that the GPU acceleration capability will be supported by this extension.

I hope you have a good day.

**Comment by silveredgold** [comment]
There's not really anyway to prevent this. The extension can only replace images with placeholders when the browser renders them, and at that point they're already on the page.

As for GPU acceleration, that's already covered in [this issue](https://github.com/silveredgold/beta-censoring/issues/20)

**Comment by tachangan** [comment]
I mean no offense, and I'm just curious. I discovered that beta safety is able to prevent uncensored image leaks before censoring is done in the same hardware environment. Is it because it supports GPU acceleration, or is it implemented in a different way?

**Comment by silveredgold** [comment]
No offense taken, no issues there. Beta Safety is slightly more reliable than Protection at that for three reasons: 

1. It's running on an outdated extension model (Manifest v2). The older MV2 spec allowed extensions more freedom about how they could run, such as running permanently in the background. However, browsers have started phasing that spec out, and the newer extension model (that Beta Protection uses) is a little more limited.
2. Whenever there's a tradeoff between performance and censoring, Beta Safety errs on the side of censoring. Protection, on the other hand, tries to hit a balance of censoring most things without slowing your browser down. While Safety's extra performance cost isn't that noticeable on more powerful hardware, it can slow the browser down on weaker hardware, so Protection tries to be a bit more friendly.
3. Similarly to the above one, Beta Safety is a bit more aggressive about hiding uncensored images than Protection is, which comes with both benefits and costs. Yes, it will prevent more "leaked" images, but it will also inadvertently hide more "safe" images, in my experience.

You're not the first person to mention this, so I will add it to the backlog of something to look into to see if I can't make it more reliable (or if anyone from the community is up to it, I'll happily accept contributions)
