### ISSUE TITLE
2 issues: Subliminal Messages & Video Censoring Preferences

### ISSUE THREAD

**Issue by PieTheSurgeon** [silveredgold/beta-protection#42]
1. Subliminal Messages will not save as a setting when the boxed is check. I have tried a bunch of scenarios and the only way it works is if you apply it and then apply another setting with a toggle switch to "save it" as a setting. Issue with both check boxes for subliminal.
2. When an override is applied, user still has ability to change Video Censoring Preferences even if the override is set to blur and "enabled" or "on demand" is selected. Image is with override installed and blur videos enabled in override. Allow and block should not be allowed. 
![1](https://user-images.githubusercontent.com/128119337/226153275-b1507cf9-f679-4937-98de-c58bc6a1eb02.png)

**Comment by silveredgold** [comment]
Thanks. I think I've fixed Video Censoring for the next release (should be out soon), I'll need to look in to the subliminal options as I don't use them myself so they don't get tested as often. Thanks for the report!

**Comment by silveredgold** [comment]
Theoretically, this has been fixed in v0.2.4. Can you try it again after updating and see if it works?

**Comment by PieTheSurgeon** [comment]
Seems to be working perfectly now. I tested a bunch and worked every time. Love the updates and the app, so thank you!
