### ISSUE TITLE
i can't create the backend localhost

### ISSUE THREAD

**Issue by nexraction** [silveredgold/beta-protection#46]
![image](https://user-images.githubusercontent.com/129372846/228840791-cea94238-0814-4174-87b1-04a7cffb55c0.png)
![image](https://user-images.githubusercontent.com/129372846/228840823-46c3bf3e-1702-4937-bab5-d19ee052263d.png)

**Comment by silveredgold** [comment]
Do you have the backend running? That second screenshot is just the build output of the extension, it doesn't include a censoring backend. Read the docs to see how to get started with a censoring backend.
