### ISSUE TITLE
v0.2.4 - Override not changing Censoring Enabled/On-Demand option initially

### ISSUE THREAD

**Issue by jesseluvsheels** [silveredgold/beta-protection#47]
When first loading an override, it aapears to not actually effect the setting in the extension menu (chrome) Shown here as applied, but not setting censoring to Enabled

![image](https://user-images.githubusercontent.com/106543602/230618271-5e3676ce-7298-43ea-8068-8fb004bfee4c.png)

If I set it to Enabled, then I cannot change it.

jesse

**Comment by silveredgold** [comment]
Thanks for the report, I'll try and reproduce it on my end as I did change a few things about the mode switching in 0.2.4
