### ISSUE TITLE
censoring not working

### ISSUE THREAD

**Issue by ghost** [silveredgold/beta-protection#5]
Thank you so much for your open source program! I downloaded the latest version of beta-protection and beta-censoring. But the browser extension shows that it cannot connect to the backend service, and the 2382 interface also shows that the socket API is not enabled. Browsing the extension also shows working abnormally, please help me!Thank you very much!
![image](https://user-images.githubusercontent.com/65658490/179750464-f734abe5-975a-438f-aa99-6559eefa0d6d.png)
![image](https://user-images.githubusercontent.com/65658490/179750456-9b6aacd3-480b-46e2-bf11-d32a5ee16e01.png)

**Comment by qiaqi** [comment]
Solved, I restarted my computer.

**Comment by Nichti** [comment]
Same problem here.
Maybe someone can tell me what backend adress Im supposed to take.
I tried with http://beta-censoring.local:2382/ but he cant connect.

**Comment by nooblobby1337** [comment]
@Nichti use http://localhost:2382

**Comment by silveredgold** [comment]
The trailing slash breaking the backend connection has been fixed in `v0.1.4`. Upgrade and hopefully that won't be an issue anymore!
