### ISSUE TITLE
Images are hidden on allowed domains

### ISSUE THREAD

**Issue by kantaiz3** [silveredgold/beta-protection#50]
Hi again! 

Firstly, thank you so much for fixing #12! However, this fix seems to have introduced a new bug 🐛. I noticed that images on some sites that are in my allowed domains list are hidden. Using dev tools I found the `visibility: hidden !important;` injected by BP on a page that should be allowed. I suspect that the issue is that my allowed "domains" aren't reeeally domains. The domain `github.com` is allowed and everything on Github works, but `bad-site.xxx/index.php?page=post&s=list` has the issue. My guess is that the code that injects the styles and the code that actually starts the censoring have slightly different domain checks.

My... unconventional... domains have a reason... On some sites, I want to allow certain pages for performance reasons. The search result pages of some sites show a bunch of really small thumbnails at once. So I allowed ***only*** the search result pages for those sites. The thumbnails were too small to really censor anyway, but took a lot of time and CPU. Allowing them made those sites nice to use while still censoring any full images.

Sooo it would be nice if my allowed "domains" would continue working... even if they are a bit unconventional...

---

I am using v0.2.6 btw

**Comment by silveredgold** [comment]
That stylesheet will always be injected, regardless of whether the page is allowed/denied/forced/whatever, that was the only way to fix #12 . Instead, the style that's injected will only apply to elements on pages where censoring is enabled.

I need more details on what images are being hidden that shouldn't be to effectively debug what you're describing.

**Comment by kantaiz3** [comment]
Sorry. I'm a bit hesitant to share URLs because of GitHub's policies...

It seems like the bug can be reproduced on most allowed sites. I did some testing and my unconventional allowed domain is irrelevant. `github.com` is in my allowed list and it happens here too. Here are 2 ways to reproduce it:
- Add `github.com` to your allow list. Go to any GitHub profile page (e.g. https://github.com/silveredgold). Refresh the page until the profile picture disappears. This might take a few reloads/hard reloads. I sometimes have to reload 10 times or more until it finally happens.
- The bad site I mentioned is rule34. Add `rule34.xxx` to your allow list. Go to the site and search for any tag (e.g. "mercy"). This will lead you to the results page where the bug frequently happens. It also happens on image pages. You may need to refresh the page or click on related tags (left) until the issue happens.

I also found the cause of the issue during my testing. The `censor-disabled` attribute isn't set on `<body>` *sometimes*. I looked at the console, and it always logs `Not censoring current page. interactive` when the bug happens and `Not censoring current page. complete` when it works correctly. Seems like BP is racing with the page load. 

I can't reproduce it on all allowed site however. E.g. I haven't been able to reproduce it on YouTube.

**Comment by kantaiz3** [comment]
I just tested the latest version and this is fixed in v0.2.7! Thank you!!
