### ISSUE TITLE
Options don't receive checkmark

### ISSUE THREAD

**Issue by b2sbeta** [silveredgold/beta-protection#51]
Ever since I updated the extension to 0.2.6. options aren't receiving a checkmark when I activate them.
For instance, I load my external placeholder images. This works without an issue. I have placeholders in 4 categories but when I go to activate a category, the category doesn't receive a check mark.
It also appears that all categories are used, even though none of have a check mark.

A similar thing happens with sticker packs. I have 3 sticker packs with an Enable/Disable toggle. Clicking to activate one, sometimes toggles the other two to on as well. Disabling them again doesn't always work. Disabling one sometimes disables another pack as well. Disabled packs are also used in censoring.

So in general, it seems some options don't save correctly.

I tried downgrading to 0.2.4. but this doesn't solve the issue. Perhaps there is something weird going on between the extension and Chromium version 112.0.5615.121? Is there something I can do to test this for you?

Just spotted a spelling issue in the options screen.
In hardcore options there is a setting called "Overwrites apply to local censoring". I think this should read "Overrides apply to local censoring".

**Comment by silveredgold** [comment]
Hmmm, I'll have to see if I can reproduce this as a few things changed in how we store preferences so it could be quite a few things. I'll try and recreate on my end and let you know if I need more testing.

Thanks for spotting that typo!

**Comment by silveredgold** [comment]
Forgot to close the loop on this, but this should be fixed in the latest versions of Beta Protection. Let me know if you can still reproduce it on the current version.

**Comment by b2sbeta** [comment]
Currently running version v0.2.10 and it looks like it's working for stickers and placeholders now!
The only place where it doesn't seem to work, is with choosing between the subtle/NSFW error image. I can active both at the same time (visually) but v0.2.10 only seems to use the NSFW error image.
