### ISSUE TITLE
None of the buttons work

### ISSUE THREAD

**Issue by tcpeine** [silveredgold/beta-protection#58]
I am running Linux(unbuntu) running brave browser.
![Screenshot from 2023-06-10 14-15-34](https://github.com/silveredgold/beta-protection/assets/136192642/99466414-ad4b-49cb-b4dc-0d9cb2aa3310)
![Screenshot from 2023-06-10 14-14-35](https://github.com/silveredgold/beta-protection/assets/136192642/965d26a5-b356-46cb-b0d0-a236ac72ab4b)
 and censoring is working just fine. But if I try to use and of the import or export buttons they do not work especially in overrides. I am only a little tech savvy so some help would be appreciated.

**Comment by silveredgold** [comment]
That's already covered in the Troubleshooting section of the [docs available here](https://silveredgold.github.io/beta-protection/guide/installation.html#troubleshooting): the Brave developers have disabled the API used by Beta Protection, there's nothing I can do from my end.
