### ISSUE TITLE
having a socket api issue

### ISSUE THREAD

**Issue by Jalapeno787** [silveredgold/beta-protection#60]
installed beta-protection using the zip file and dragged that in as chrome was being pissy about the .crx file, beta censoring seems to work but when I check server status I'm getting socket api not working. 
![image](https://github.com/silveredgold/beta-protection/assets/107211244/dd6a683a-29ba-425e-bd04-de19bf642d55)

**Comment by Jalapeno787** [comment]
I've got beta-protection v0.2.6 and censoring 0.0.9

**Comment by Jalapeno787** [comment]
ive got protection 0.2.6 and censoring 0.0.9

**Comment by silveredgold** [comment]
Unless you actually need the Socket API (which Beta Protection doesn't use) that's fine. You only need that API running if you are using it for another client or something like that.
