### ISSUE TITLE
Maybe helpful trying to fix a speficic crash

### ISSUE THREAD

**Issue by nisaeggu** [silveredgold/beta-protection#62]
When I installed beta protection in google chrome I've gone into the option to change some censoring options. My browser began to freeze due to beta protection adjusting and saving the settings in the censoring options repeatedly, which was indicated by the extention interface spawning a ridiculous amounts of "Saved!" notifications. This might be the cause of crashes in vivaldi as well.

**Comment by silveredgold** [comment]
Thanks for the info! The crashes are being tracked in #53 , and that is helpful. I think I've narrowed down the cause of both the notification floods and the crashes (related, but not the same issue) and this should be at least mitigated in the next release. Thanks for the report!
