### ISSUE TITLE
Need to load page twice to show images on allowed sites and/or when censoring is disabled

### ISSUE THREAD

**Issue by guyr1347** [silveredgold/beta-protection#63]
Small but annoying bug, on some websites, that are either allowed, or when I have turned censoring off, they will not show their images until I refresh the page. I have to reload the webpage every time when loading a new page, not just the first time after I change the setting.
Am using Beta protection + beta censoring on chrome, Win10.

**Comment by silveredgold** [comment]
Thanks for the report, this should be resolved in the next update! We refactored how images are handled to fix another user's request (#39 ) and it turned out to be a little over-zealous.
