### ISSUE TITLE
Censoring Does Not Work On Lemmy 

### ISSUE THREAD

**Issue by saltedcheesecake** [silveredgold/beta-protection#70]
Hello @silveredgold, it appears that beta-protection censoring does not work for Lemmy-based sites.

Steps to reproduce on Chrome (v116) / Windows 11 :
1. Run `betacensor-server-win-x64.v0.0.11`
2. Install `beta-protection-v0.2.10-production` using `.crx`.
3. Browse some NSFW site, e.g., javdb dot com -> censoring works.
4. Browse to an NSFW Lemmy instance, e.g., lemmynsfw dot com, expand any post -> censoring does not apply.

Looking forward to any testing you might do to reproduce the issue. Thank you for the effort.

**Comment by silveredgold** [comment]
Hmmm, I'll have to sign up for an account on that instance to test that as I browse Lemmy instances through Mastodon and they're correctly censored. Must be something about Lemmy's UI specifically.

**Comment by saltedcheesecake** [comment]
Thank you, let me know if you need further help testing, much appreciated

**Comment by silveredgold** [comment]
I can't reproduce this. I've got an account on the server you mentioned (lemmynsfw) and when I expand images inline, they are censored correctly.

Are you sure censoring is enabled for the page when you're browsing Lemmy?

**Comment by saltedcheesecake** [comment]
> 

Thanks for testing it out, appreciate it. I checked that the censoring is enabled.

I'm attaching a screen cap in case you'll find it useful here: 

(zip wraps a 7z file containing an .mp4) 

[lemmy.zip](https://github.com/silveredgold/beta-protection/files/12533446/lemmy.zip)

Let me know if it helps, but otherwise I suppose Lemmy is out for now at least for me.

**Comment by saltedcheesecake** [comment]
I can't send a private message with the 7z password since GitHub no longer supports it, but if you have any way to drop you an ephemeral message (like a burner email), let me know.

**Comment by silveredgold** [comment]
Easiest way is you can send it to my github username `@protonmail.com`, or put it in a gist and email the link to that or whatever

**Comment by saltedcheesecake** [comment]
> Easiest way is you can send it to my github username `@protonmail.com`, or put it in a gist and email the link to that or whatever

Sent, thank you very much for the effort.

**Comment by silveredgold** [comment]
That's very odd as I can recreate that process step-for-step on my system and it censors correctly when images are expanded. When images fail to censor, is there any error messages/output from the backend?

**Comment by saltedcheesecake** [comment]
> That's very odd as I can recreate that process step-for-step on my system and it censors correctly when images are expanded. When images fail to censor, is there any error messages/output from the backend?

Not that I can see, I added the text output with another video in here (same password): 
[lemmy.zip](https://github.com/silveredgold/beta-protection/files/12543864/lemmy.zip)

Its a fresh browser with no other plugins. I thought it was a Chrome thing so I used another Chrome-based browser (https://tempest.com/browser), but on Chrome, the behavior is identical. Cheers mate.

**Comment by silveredgold** [comment]
[lemmy_local.zip](https://github.com/silveredgold/beta-protection/files/12544122/lemmy_local.zip)

Just so you can see what I mean, here's what I'm doing to try and reproduce what you're seeing but it just censors no issues for me on Edge (also Chrome-based). Same password.

**Comment by saltedcheesecake** [comment]
> [lemmy_local.zip](https://github.com/silveredgold/beta-protection/files/12544122/lemmy_local.zip)
> 
> Just so you can see what I mean, here's what I'm doing to try and reproduce what you're seeing but it just censors no issues for me on Edge (also Chrome-based). Same password.

Ahh, shucks I might be SOL then. It should be a combination of very edge-case settings that is not taking well to the extension. But still, appreciate the work very much, I'll just skip over Lemmy for now. Cheers mate.

**Comment by saltedcheesecake** [comment]
Can't reproduce, closing for now.

**Comment by silveredgold** [comment]
The only other thing I can think of is to have a look in the browser console (i.e. press F12 for DevTools > Console tab) and see if there's any obvious errors coming from Beta Protection, maybe? Sorry I can't be of more help here but when I can't get _anything_ to happen on my end it's tricky to work out what might be causing it.

**Comment by saltedcheesecake** [comment]
> The only other thing I can think of is to have a look in the browser console (i.e. press F12 for DevTools > Console tab) and see if there's any obvious errors coming from Beta Protection, maybe? Sorry I can't be of more help here but when I can't get _anything_ to happen on my end it's tricky to work out what might be causing it.

No worries at all. I just checked the console and it doesn't appear to throw any exceptions that are out of the ordinary. But all good, I still appreciate the effort tremendously. In any case it still works with most other sites so those are admissible.
